version: "3.5"

networks:
  simpledocker-network:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  php74-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=7.4
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./src:/usr/share/nginx/html/
    ports:
      - "9007:9001"
    expose:
      - "9000"
    networks:
      - simpledocker-network

  php8-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=8
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./src:/usr/share/nginx/html/
    ports:
      - "9008:9001"
    expose:
      - "9000"
    networks:
      - simpledocker-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
    networks:
      - simpledocker-network
